name: 4-Deploy-QA-DAST-Scan

# Only triggers manually or when the build "2-Build and Publish Docker Image" workflow succeeds

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["2-Dockerize-Publish"]
    types:
      - completed
      
# Deploy and run the Docker image for QA and DAST testing
jobs:
  Deploy-Docker-Image-QA-Server:
    runs-on: [self-hosted]
    steps:         
      - name: Terminate previous QA Docker image to run new version
        run: |
         docker stop verademo-dotnetcore-github
         docker rm verademo-dotnetcore-github
        continue-on-error: true
       
# Pull new Docker image to QA web server
      - name: Pull new Docker image to QA web server
        run: |
         docker pull veracodedemolabs/verademo-dotnetcore-github:latest
         
# Run Docker image on QA webserver for testing
      - name: Run Docker image
        run: |
         docker run --rm -d --name verademo-dotnetcore-github -p 8081:8080 veracodedemolabs/verademo-dotnetcore-github:latest
         
